apiVersion: v1
kind: Service
metadata:
  name: spark
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: spark-master
    port: 7077
    targetPort: 7077
  selector:
    app: spark
